import {test,expect,type Page} from '@playwright/test';
import {ready,reachable,fitsScreen} from '../helpers/mobile-ui';
async function contrast(page:Page,selector:string,background:string){
 const ratio=await page.evaluate(({selector,background}:{selector:string,background:string})=>{
  const read=(s:string)=>s.match(/[\d.]+/g)!.slice(0,3).map(Number).map(v=>{v/=255;return v<=.04045?v/12.92:Math.pow((v+.055)/1.055,2.4);});
  const a=read(getComputedStyle(document.querySelector(selector)!).color),b=read(getComputedStyle(document.querySelector(background)!).backgroundColor),l=(v:number[])=>.2126*v[0]+.7152*v[1]+.0722*v[2];return (Math.max(l(a),l(b))+.05)/(Math.min(l(a),l(b))+.05);
 },{selector,background});expect(ratio,selector+' contrast').toBeGreaterThanOrEqual(4.5);
}
for(const viewport of [{width:320,height:500},{width:390,height:844},{width:1440,height:900}])test.describe(`beach light palette ${viewport.width}`,()=>{
 test.use({viewport,isMobile:viewport.width<800,hasTouch:viewport.width<800});
 test('insufficient currency, draw result and event dialogs remain readable',async({page},info)=>{
  await ready(page);const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.locator('.game-dock [data-action=recruitment]').click();await fitsScreen(page);await expect(page.locator('[data-action=draw]')).toBeDisabled();await expect(page.locator('[data-action=draw]')).toHaveCSS('opacity','1');await contrast(page,'.recruit-item h2','.recruit-item');await contrast(page,'.recruit-item-rate','.recruit-item');await contrast(page,'[data-action=draw]','[data-action=draw]');await contrast(page,'.hud-resources b','.game-hud');await contrast(page,'.hud-resources small','.game-hud');await contrast(page,'.hud-commander-progress small','.game-hud');await page.waitForTimeout(500);await page.screenshot({path:info.outputPath(`light-insufficient-${viewport.width}.png`)});
  await page.locator('[data-action=recruit-tab][data-id=exchange]').click();await expect(page.locator('[data-action=exchange]').first()).toBeDisabled();await contrast(page,'[data-action=exchange]','[data-action=exchange]');await page.screenshot({path:info.outputPath(`light-exchange-disabled-${viewport.width}.png`)});
  await page.locator('.recruit-help').click();await expect(page.locator('.command-dialog')).toBeVisible();await contrast(page,'.command-dialog h2','.command-dialog');await page.screenshot({path:info.outputPath(`light-rules-${viewport.width}.png`)});await page.locator('.command-dialog [data-action=command-close]').first().click();
  await page.evaluate(async()=>{window.__game.getSave().collection.tickets=1;await window.__game.save();window.__game.route('recruitment');});await page.locator('[data-action=recruit-tab][data-id=draw]').click();await reachable(page.locator('[data-action=draw]'));await expect(page.locator('[data-action=draw]')).toBeEnabled();await expect(page.locator('[data-action=draw]')).toHaveCSS('color','rgb(255, 255, 255)');await expect(page.locator('[data-action=draw]')).toHaveCSS('background-image',/12, 114, 131/);await page.screenshot({path:info.outputPath(`light-ready-${viewport.width}.png`)});await page.locator('[data-action=draw]').click();
  const receiptButton=page.getByRole('button',{name:'招募結果',exact:true});if(viewport.width<800)await receiptButton.click();await expect(page.locator('.recruitment-receipt')).toBeVisible();await page.screenshot({path:info.outputPath(`light-result-${viewport.width}.png`)});expect(await page.evaluate(()=>window.__game.getSave().collection.tickets)).toBe(0);expect(await page.evaluate(()=>window.__game.getSave().collection.lastReceipt?.formId)).toBeTruthy();
  if(await page.locator('dialog.mobile-detail[open]').count())await page.keyboard.press('Escape');await page.locator('.recruit-card-grid [data-action=recruit-preview]').first().click();await expect(page.locator('.recruit-art-viewer')).toBeVisible();await contrast(page,'.recruit-art-viewer h2','.recruit-art-viewer');await page.screenshot({path:info.outputPath(`light-art-${viewport.width}.png`)});await page.getByRole('button',{name:'關閉大圖'}).click();await page.locator('.game-dock [data-action=home]').click();expect(await page.locator('#app').evaluate(e=>getComputedStyle(e).backgroundColor)).not.toBe('rgb(229, 244, 244)');expect(errors).toEqual([]);
 });
});
