import { assetUrl } from '../assets';
import { deepTreesFor, DEEP_NODE_MAP, COMMON_TREE } from '../data/deep-trees';
import { deepGraph } from './deep-tree';
import { treesFor } from '../data/skill-trees';
import { RANGE_LABEL, WEAPON_RANGE } from '../sim/range';
import { CHARACTERS, CHARACTER_MAP, ROUTES, STAGES, STAGE_MAP, ENEMIES, ENEMY_MAP, BUILDS } from '../data/content';
import type { GameSave } from '../storage/repository';
import type { ViewModel } from './model';
import type { CharacterId } from '../sim/types';
import { esc, portrait, roleTags, clock, num } from './format';

export function header(page: string, saveStatus: string) {
  return `<header class="masthead"><button class="wordmark" data-action="home" aria-label="回到主頁"><span class="brand-star">✦</span><span>星骸防線<small>STARFALL / DAWN COUNTERATTACK</small></span></button><div class="masthead-right"><span class="local-status" aria-live="polite"><i></i>${esc(saveStatus)}</span><button class="icon-button" data-action="settings" aria-label="設定">⚙</button></div></header><nav class="main-nav" aria-label="主選單">${[['home', '作戰中心'], ['roster', '小隊編成'], ['codex', '科技圖鑑'], ['stories', '反攻紀錄']].map(([id, label]) => `<button data-action="${id}" ${page === id ? 'aria-current="page" class="active"' : ''}>${label}</button>`).join('')}</nav>`;
}
export function home(save: GameSave, vm: ViewModel) {
  const stage = STAGE_MAP[vm.stageId]; const captain = CHARACTER_MAP[save.preferences.captainId];
  return `<main class="home-screen"><section class="hero"><div class="hero-scenery" style="background-image:url('${assetUrl(`stages/${vm.stageId}.webp`)}')"></div><div class="hero-type"><div class="eyebrow"><span class="pulse-dot"></span>EARTH DEFENSE FORCE · 01</div><h1>為了明天，<br>向星骸<span>反攻。</span></h1><p>她們守住的，<br>是整座城市的黎明。</p><div class="hero-caption"><span>NO GRIND. ALL STRATEGY.</span><b>六位少女 · 150 個構築節點</b></div></div>${portrait(captain.id, 'hero-character')}<span class="hero-character-label">${esc(captain.english.toUpperCase())}<small>${esc(captain.name)} / FIELD LEADER</small></span><span class="hero-index">// DAWN PROTOCOL</span></section>
  <section class="operation-panel"><div class="section-kicker">NEXT OPERATION <span>0${Number(vm.stageId.slice(1))} / 03</span></div><div class="operation-title"><div><h2>${esc(stage.name)}</h2><p>${esc(stage.subtitle)}</p></div><span class="duration">06–08<small>MINUTES</small></span></div><div class="stage-selector" aria-label="選擇關卡">${STAGES.map((s, i) => { const unlocked = i === 0 || save.profile.cleared.includes(STAGES[i - 1].id); return `<button class="${s.id === vm.stageId ? 'selected' : ''}" data-action="stage" data-id="${s.id}" ${!unlocked ? 'disabled' : ''}><span>0${i + 1}</span>${esc(s.name)}<small>${save.profile.cleared.includes(s.id) ? '✓ 已奪回' : unlocked ? '可出擊' : '▣ 尚未解鎖'}</small></button>`; }).join('')}</div><div class="squad-ribbon"><span>目前編隊</span><div>${save.preferences.squadIds.map(id => `<button data-action="character" data-id="${id}" aria-label="查看${esc(CHARACTER_MAP[id].name)}">${portrait(id)}${save.preferences.captainId === id ? '<b>★</b>' : ''}</button>`).join('')}</div><button class="text-button" data-action="roster">調整 ↗</button></div>
  ${save.activeRun && save.activeRun.phase !== 'ended' ? `<div class="resume-banner"><span><b>防線仍在等妳</b><small>${esc(STAGE_MAP[save.activeRun.config.stageId].name)} · ${clock(save.activeRun.tick)}</small></span><button class="button primary" data-action="continue">繼續行動 →</button></div>` : `<button class="button primary deploy-button" data-action="intel"><span>開始行動</span><span>DEPLOY →</span></button>`}<p class="quiet-note">所有角色與武器路線已開放。勝負，由妳的搭配決定。</p></section></main>`;
}
export function intel(save: GameSave, vm: ViewModel) {
  const stage = STAGE_MAP[vm.stageId]; const boss = ENEMY_MAP[stage.bossId];
  return `<main class="content-screen"><div class="page-intro"><span class="eyebrow">OPERATION BRIEFING / ${vm.stageId}</span><h1>${esc(stage.name)}</h1><p>${esc(stage.description)}</p></div><section class="intel-banner" style="background-image:url('${assetUrl(`stages/${stage.id}.webp`)}')"><span>MISSION OBJECTIVE</span><h2>守住防線，擊破入侵核心</h2><p>8 波敵群 · 06:00 首領降臨 · 08:00 行動期限</p></section><div class="briefing-dialogue">${stage.intro.map(line => `<p>${esc(line)}</p>`).join('')}</div><div class="intel-columns"><section><h2 class="section-heading">威脅情報 <small>提前了解，從容反制</small></h2><div class="enemy-grid">${stage.enemyIds.filter(id => !id.startsWith("B")).map(id => { const e = ENEMY_MAP[id]; return `<article class="enemy-info"><img src="${assetUrl(`enemies/${id}.webp`)}" alt="${esc(e.name)}"><div><h3>${esc(e.name)}</h3><p>${esc(e.mechanic)}</p><strong>對策 / ${esc(e.counter)}</strong></div></article>`; }).join('')}</div></section><aside class="boss-info"><span class="eyebrow">PRIORITY TARGET</span><img src="${assetUrl(`enemies/${boss.id}.webp`)}" alt="${esc(boss.name)}"><h2>${esc(boss.name)}</h2><p>${esc(boss.mechanic)}</p><strong>${esc(boss.counter)}</strong></aside></div>${save.profile.cleared.includes(stage.id) ? `<section class="challenge-select"><h2 class="section-heading">選擇挑戰 <small>沒有戰力獎勵，只為更好的決策</small></h2><div class="segmented">${[['', '標準行動'], ['four', '最多四人'], ['no-skill', '禁用隊長技能'], ['two-evolutions', '最多兩把進化']].map(([id, label]) => `<button class="${(vm.challengeId ?? '') === id ? 'selected' : ''}" data-action="challenge" data-id="${id}">${label}${save.profile.challengeClears.includes(`${stage.id}:${id}`) ? ' ✓' : ''}</button>`).join('')}</div></section>` : ''}<div class="action-bar"><button class="button secondary" data-action="home">返回</button><button class="button primary" data-action="roster">確認情報 · 編成小隊 →</button></div></main>`;
}
export function roster(save: GameSave, vm: ViewModel) {
  const prefs = save.preferences; const max = vm.challengeId === 'four' ? 4 : 5;
  const tags = [...new Set(prefs.squadIds.flatMap(id => roleTags[id]))];
  return `<main class="content-screen roster-screen"><div class="page-intro"><span class="eyebrow">SQUAD FORMATION</span><h1>每個選擇，都有她的主場。</h1><p>選擇 1–${max} 位隊員，任命一位隊長。每人有 2～3 條技能樹，另有全隊共用樹。依經驗取得技能點，自由搭配。</p></div><section class="formation-strip"><div class="formation-slots">${Array.from({ length: max }, (_, i) => { const id = prefs.squadIds[i]; return id ? `<button data-action="toggle-character" data-id="${id}" class="filled-slot" aria-label="移除${esc(CHARACTER_MAP[id].name)}">${portrait(id)}<span>${prefs.captainId === id ? '★ ' : ''}${esc(CHARACTER_MAP[id].name)}</span></button>` : `<span class="empty-slot" aria-label="空出戰位置">${String(i + 1).padStart(2, '0')}<small>待命</small></span>`; }).join('')}</div><div class="formation-capabilities"><b>能力覆蓋</b>${['清群', '對甲', '對盾', '控場', '支援'].map(t => `<span class="${tags.includes(t) ? 'present' : 'absent'}">${tags.includes(t) ? '✓' : '—'} ${t}</span>`).join('')}<small>依武器特性顯示，沒有虛構戰力分數。</small></div></section>
  <div class="recommendations"><span>搭配靈感</span>${BUILDS.map(b => `<button data-action="build" data-id="${b.id}">${esc(b.name)} ↗</button>`).join('')}</div><div class="roster-grid">${CHARACTERS.map(c => { const chosen = prefs.squadIds.includes(c.id); return `<article class="character-card ${chosen ? 'chosen' : ''}" style="--character:${c.color}"><button class="character-art" data-action="character" data-id="${c.id}" aria-label="查看${esc(c.name)}的角色與武器">${portrait(c.id)}<span class="character-code">${c.id} / ${esc(c.english.toUpperCase())}</span><span class="character-role">${esc(c.role)}</span></button><div class="character-card-body"><div class="character-title"><h2>${esc(c.name)}</h2><button class="add-character ${chosen ? 'selected' : ''}" data-action="toggle-character" data-id="${c.id}" aria-label="${chosen ? '移除' : '選擇'}${esc(c.name)}" ${!chosen && prefs.squadIds.length >= max ? 'disabled' : ''}>${chosen ? '✓ 出戰' : '＋ 加入'}</button></div><p>${esc(c.weaponName)} · ${RANGE_LABEL[c.id]}</p><div class="character-controls"><button class="captain-button ${prefs.captainId === c.id ? 'selected' : ''}" data-action="captain" data-id="${c.id}" ${!chosen ? 'disabled' : ''}>${prefs.captainId === c.id ? '★ 隊長' : '☆ 任命隊長'}</button><button class="text-button" data-action="character" data-id="${c.id}">查看 ${treesFor(c.id).length} 條技能樹 ↗</button></div></div></article>`; }).join('')}</div><div class="action-bar sticky-action"><span><b>${prefs.squadIds.length} / ${max}</b> 位隊員 <small>${esc(STAGE_MAP[vm.stageId].name)}</small></span><button class="button primary" data-action="start" ${prefs.squadIds.length < 1 || prefs.squadIds.length > max ? 'disabled' : ''}>全員就位 · 出擊 →</button></div></main>`;
}
export function codex(save: GameSave, vm: ViewModel) {
  const c = CHARACTER_MAP[vm.characterId];
  return `<main class="content-screen codex-screen"><div class="page-intro"><span class="eyebrow">TECH & PERSONNEL ARCHIVE</span><h1>她們，與改寫戰局的科技。</h1></div><div class="character-tabs" role="group" aria-label="選擇圖鑑角色">${CHARACTERS.map(ch => `<button class="${ch.id === c.id ? 'selected' : ''}" data-action="character" data-id="${ch.id}">${portrait(ch.id)}<span>${esc(ch.name)}</span></button>`).join('')}</div><section class="dossier" style="--character:${c.color}"><div class="dossier-art">${portrait(c.id)}<span>${esc(c.english.toUpperCase())}</span></div><div class="dossier-copy"><span class="eyebrow">${c.id} / ${c.age} 歲 / ${esc(c.role)}</span><h2>${esc(c.name)} <small>${esc(c.english)}</small></h2><p class="character-description">${esc(c.description)}</p><section class="weapon-info"><img src="${assetUrl(`weapons/${c.id}.webp`)}" alt="${esc(c.weaponName)}"><div><span class="eyebrow">ALIEN-ADAPTED TECHNOLOGY</span><h3>${esc(c.weaponName)}</h3><p>${RANGE_LABEL[c.id]} · 射程 ${WEAPON_RANGE[c.id]} · 基礎傷害 ${c.damage} · 間隔 ${c.interval} 秒</p></div></section><dl class="skill-definitions"><div><dt>被動能力</dt><dd>${esc(c.passive)}</dd></div><div><dt>隊長技能 · ${esc(c.tacticalName)}</dt><dd>${esc(c.tacticalDescription)}<small>冷卻 ${c.cooldown} 秒，新局先完成一次冷卻。</small></dd></div></dl></div></section><section class="route-comparison"><h2 class="section-heading">${deepTreesFor(c.id).length} 條技能樹，自由搭配 <small>各樹 8～12 節點 · 本樹先投入 4 點，再沿前置取得終極。</small></h2><div class="route-columns">${deepTreesFor(c.id).map(t=>`<article class="deep-codex-tree"><h3>${esc(t.name)} <small>${t.nodes.length} 節點</small></h3><p>${esc(t.purpose)}</p>${deepGraph(t,undefined,vm.codexNode)}</article>`).join('')}</div><details class="common-codex"><summary>全隊共用技能 · 12 節點</summary>${deepGraph(COMMON_TREE,undefined,vm.codexNode)}</details><div id="codex-node-detail" class="codex-node-detail" aria-live="polite">${vm.codexNode&&DEEP_NODE_MAP[vm.codexNode]?`<h3>${esc(DEEP_NODE_MAP[vm.codexNode].name)}</h3><p>${esc(DEEP_NODE_MAP[vm.codexNode].description)}</p><small>前置：${DEEP_NODE_MAP[vm.codexNode].parents.map(id=>esc(DEEP_NODE_MAP[id].name)).join(' 或 ')||'入口，可直接取得'}${DEEP_NODE_MAP[vm.codexNode].kind==='ultimate'?'；本樹先投入 4 點，並占用一個終極名額':''}</small>`:'<p>點選任意節點，查看完整效果與前置。</p>'}</div><p class="tradeoff">每個節點 1 點，每局最多 24 點。每人一個終極、全隊最多三個；共用樹不占名額。</p></section><section class="enemy-codex"><h2 class="section-heading">外星生命紀錄 <small>已遭遇 ${save.profile.seenEnemies.length} / ${ENEMIES.length}</small></h2><div class="enemy-grid">${ENEMIES.map(e => `<article class="enemy-info ${save.profile.seenEnemies.includes(e.id) ? '' : 'unseen'}"><img src="${assetUrl(`enemies/${e.id}.webp`)}" alt="${esc(e.name)}"><div><h3>${esc(e.name)} <small>${save.profile.seenEnemies.includes(e.id) ? '已遭遇' : '情報預覽'}</small></h3><p>${esc(e.mechanic)}</p><strong>${esc(e.counter)}</strong></div></article>`).join('')}</div></section></main>`;
}
export function stories(save: GameSave) {
  return `<main class="content-screen"><div class="page-intro"><span class="eyebrow">COUNTERATTACK JOURNAL</span><h1>黎明，從未獨自到來。</h1><p>每一道奪回的防線，都是她們留下的故事。</p></div><div class="journal">${STAGES.map((s, i) => `<article class="journal-entry ${save.profile.cleared.includes(s.id) ? 'unlocked' : ''}"><img src="${assetUrl(`stages/${s.id}.webp`)}" alt="${esc(s.name)}"><div><span class="eyebrow">CHAPTER 0${i + 1}</span><h2>${esc(s.name)}</h2>${save.profile.cleared.includes(s.id) ? [...s.intro, ...s.outro].map(line => `<p>${esc(line)}</p>`).join('') : `<p>首次完成本關後，解鎖行動紀錄。</p><span class="lock-label">▣ 尚未完成</span>`}</div></article>`).join('')}</div><section class="recent-runs"><h2 class="section-heading">最近行動</h2>${save.profile.recentRuns.length ? `<div class="table-scroll"><table><thead><tr><th>關卡</th><th>結果</th><th>時間</th><th>防線</th></tr></thead><tbody>${save.profile.recentRuns.map(r => `<tr><td>${esc(STAGE_MAP[r.stageId].name)}</td><td>${r.outcome === 'victory' ? '奪回成功' : r.outcome === 'abandoned' ? '撤退' : '防守失敗'}</td><td>${clock(r.tick)}</td><td>${num(r.wallHp)}</td></tr>`).join('')}</tbody></table></div>` : '<p class="empty-state">第一次出擊，就是故事的起點。</p>'}</section></main>`;
}
export function settings(save: GameSave, status: string, embedded = false) {
  return `<section class="${embedded ? 'embedded-settings' : 'content-screen settings-screen'}">${embedded ? '<h2>音效與顯示</h2>' : '<div class="page-intro"><span class="eyebrow">SYSTEM PREFERENCES</span><h1>依照妳的節奏。</h1></div>'}<div class="setting-row"><label for="music">音樂<small>原創合成配樂</small></label><input id="music" data-change="music" type="range" min="0" max="1" step="0.05" value="${save.preferences.musicVolume}" aria-label="音樂音量"></div><div class="setting-row"><label for="sfx">音效<small>武器、命中與危險提示</small></label><input id="sfx" data-change="sfx" type="range" min="0" max="1" step="0.05" value="${save.preferences.sfxVolume}" aria-label="音效音量"></div><div class="setting-row"><label for="reduced">減少特效<small>降低粒子與動態；不影響戰鬥規則</small></label><input id="reduced" data-change="reduced" type="checkbox" ${save.preferences.reducedEffects ? 'checked' : ''}></div><div class="setting-row"><label for="auto-tactical">自動施放隊長技能<small>場上有敵人且技能就緒時施放</small></label><input id="auto-tactical" data-change="auto-tactical" type="checkbox" ${save.preferences.autoTactical ? 'checked' : ''}></div>${embedded ? '' : `<div class="save-information"><span class="eyebrow">LOCAL SAVE</span><h2>${esc(status)}</h2><p>進度保存在目前瀏覽器。相同網址可繼續；換裝置或清除網站資料不會同步。</p><button class="button secondary" data-action="save-retry" ${status.startsWith('暫時') ? 'disabled' : ''}>立即儲存</button></div><div class="danger-zone"><span><b>重置本機進度</b><small>刪除關卡紀錄、設定及進行中的行動。</small></span><button class="button danger" data-action="reset-confirm">重置進度</button></div><button class="button secondary" data-action="home">返回作戰中心</button>`}</section>`;
}
