import { offlineSettings } from './offline';
import {commanderProgress} from '../data/commander';
import {commanderState} from './commander';
import { stageProfile } from '../data/progression';
import { challengesUnlocked } from '../storage/mission-rewards';
import { assetUrl } from '../assets';
import { stageArt, chapterName } from '../data/campaign';
import { WEAKNESSES, formPortrait, originalForm } from '../data/forms';
import { elementBadge, formControls } from './collection';
import { RANGE_LABEL, WEAPON_RANGE } from '../sim/range';
import { CHARACTERS, CHARACTER_MAP, STAGES, STAGE_MAP, ENEMIES, ENEMY_MAP } from '../data/content';
import type { GameSave } from '../storage/repository';
import type { ViewModel } from './model';
import { esc, portrait, clock, num } from './format';

export function intel(save: GameSave, vm: ViewModel) {
  const stage = STAGE_MAP[vm.stageId],profile=stageProfile(vm.stageId); const boss = ENEMY_MAP[stage.bossId];
  return `<main class="content-screen"><div class="page-intro"><span class="eyebrow">OPERATION BRIEFING / ${vm.stageId}</span><h1>${esc(stage.name)}</h1><p>${esc(stage.description)}</p></div><section class="intel-banner" style="background-image:url('${stageArt(stage.id)}')"><span>MISSION OBJECTIVE</span><h2>守住防線，擊破入侵核心</h2><p>${profile.waves.length} 波敵群 · ${profile.enemies} 隻 · ${profile.points} 點技能 · ${clock(profile.bossAt*30)} 首領降臨 · ${clock(profile.deadline*30)} 行動期限</p></section><div class="briefing-dialogue">${stage.intro.map(line => `<p>${esc(line)}</p>`).join('')}</div><div class="intel-columns"><section><h2 class="section-heading">威脅情報 <small>提前了解，從容反制</small></h2><div class="enemy-grid">${stage.enemyIds.filter(id => !id.startsWith("B")).map(id => { const e = ENEMY_MAP[id]; return `<article class="enemy-info"><img src="${assetUrl(`enemies/${id}.webp`)}" alt="${esc(e.name)}"><div><h3>${esc(e.name)}</h3><p>${esc(e.mechanic)}</p>${elementBadge(WEAKNESSES[e.id],true)}<strong>對策 / ${esc(e.counter)}</strong></div></article>`; }).join('')}</div></section><aside class="boss-info"><span class="eyebrow">PRIORITY TARGET</span><img src="${assetUrl(`enemies/${boss.id}.webp`)}" alt="${esc(boss.name)}"><h2>${esc(boss.name)}</h2><p>${esc(boss.mechanic)}</p>${elementBadge(WEAKNESSES[boss.id],true)}<strong>${esc(boss.counter)}</strong></aside></div>${challengesUnlocked(save,stage.id) ? `<section class="challenge-select"><h2 class="section-heading">選擇挑戰 <small>各挑戰耐久三格獎勵為 3／6／9 張招募券，每格只領一次</small></h2><div class="segmented">${[['', '標準行動'], ['four', '最多四人'], ['no-skill', '禁用隊長技能'], ['two-evolutions', '最多兩個終極']].map(([id, label]) => `<button class="${(vm.challengeId ?? '') === id ? 'selected' : ''}" data-action="challenge" data-id="${id}">${label}${save.profile.challengeClears.includes(`${stage.id}:${id}`) ? ' ✓' : ''}</button>`).join('')}</div></section>` : ''}<div class="action-bar"><button class="button secondary" data-action="home">返回</button><button class="button primary" data-action="start">開始作戰 →</button></div></main>`;
}
export function codex(save: GameSave, vm: ViewModel) {
  const c = CHARACTER_MAP[vm.characterId];
  return `<main class="content-screen codex-screen"><div class="page-intro"><span class="eyebrow">TECH & PERSONNEL ARCHIVE</span><h1>她們，與改寫戰局的科技。</h1></div><div class="character-tabs" role="group" aria-label="選擇圖鑑角色">${CHARACTERS.map(ch => `<button class="${ch.id === c.id ? 'selected' : ''}" data-action="character" data-id="${ch.id}">${portrait(ch.id)}<span>${esc(ch.name)}</span></button>`).join('')}</div><section class="dossier" style="--character:${c.color}"><div class="dossier-art">${portrait(c.id)}<span>${esc(c.english.toUpperCase())}</span></div><div class="dossier-copy"><span class="eyebrow">${c.id} / ${c.age} 歲 / ${esc(c.role)}</span><h2>${esc(c.name)} <small>${esc(c.english)}</small></h2><p class="character-description">${esc(c.description)}</p><section class="weapon-info"><img src="${c.id==='C07'||c.id==='C08'?formPortrait(originalForm(c.id)):assetUrl('weapons/'+c.id+'.webp')}" alt="${esc(c.weaponName)}"><div><span class="eyebrow">ALIEN-ADAPTED TECHNOLOGY</span><h3>${esc(c.weaponName)}</h3><p>${RANGE_LABEL[c.id]} · 射程 ${WEAPON_RANGE[c.id]} · 基礎傷害 ${c.damage} · 間隔 ${c.interval} 秒</p></div></section>${formControls(save,c.id)}<dl class="skill-definitions"><div><dt>被動能力</dt><dd>${esc(c.passive)}</dd></div><div><dt>隊長技能 · ${esc(c.tacticalName)}</dt><dd>${esc(c.tacticalDescription)}<small>冷卻 ${c.cooldown} 秒，新局先完成一次冷卻。</small></dd></div></dl></div></section><button class="button secondary personnel-skills-trigger" data-action="personnel-skills" data-id="${c.id}" aria-haspopup="dialog">技能樹與節點</button><section class="enemy-codex"><h2 class="section-heading">外星生命紀錄 <small>已遭遇 ${save.profile.seenEnemies.length} / ${ENEMIES.length}</small></h2><div class="enemy-grid">${ENEMIES.map(e => `<article class="enemy-info ${save.profile.seenEnemies.includes(e.id) ? '' : 'unseen'}"><img src="${assetUrl(`enemies/${e.id}.webp`)}" alt="${esc(e.name)}"><div><h3>${esc(e.name)} <small>${save.profile.seenEnemies.includes(e.id) ? '已遭遇' : '情報預覽'}</small></h3><p>${esc(e.mechanic)}</p>${elementBadge(WEAKNESSES[e.id],true)}<strong>${esc(e.counter)}</strong></div></article>`).join('')}</div></section></main>`;
}
export function stories(save: GameSave) {
  return `<main class="content-screen"><div class="page-intro"><span class="eyebrow">COUNTERATTACK JOURNAL</span><h1>黎明，從未獨自到來。</h1><p>每一道奪回的防線，都是她們留下的故事。</p></div><div class="journal">${STAGES.map(s => `<article class="journal-entry ${save.profile.cleared.includes(s.id) ? 'unlocked' : ''}"><img src="${stageArt(s.id)}" alt="${esc(s.name)}"><div><span class="eyebrow">${esc(chapterName(s.id))} / ${s.id}</span><h2>${esc(s.name)}</h2>${save.profile.cleared.includes(s.id) ? [...s.intro, ...s.outro].map(line => `<p>${esc(line)}</p>`).join('') : `<p>首次完成本關後，解鎖行動紀錄。</p><span class="lock-label">▣ 尚未完成</span>`}</div></article>`).join('')}</div><section class="recent-runs"><h2 class="section-heading">最近行動</h2>${save.profile.recentRuns.length ? `<div class="table-scroll"><table><thead><tr><th>關卡</th><th>結果</th><th>時間</th><th>防線</th></tr></thead><tbody>${save.profile.recentRuns.map(r => `<tr><td>${esc(STAGE_MAP[r.stageId].name)}</td><td>${r.outcome === 'victory' ? '奪回成功' : r.outcome === 'abandoned' ? '撤退' : '防守失敗'}</td><td>${clock(r.tick)}</td><td>${num(r.wallHp)}</td></tr>`).join('')}</tbody></table></div>` : '<p class="empty-state">第一次出擊，就是故事的起點。</p>'}</section></main>`;
}
export function settings(save: GameSave, status: string, embedded = false) {
  return `<section class="${embedded ? 'embedded-settings' : 'content-screen settings-screen'}">${embedded ? '<h2>音效與顯示</h2>' : '<div class="page-intro"><span class="eyebrow">SYSTEM PREFERENCES</span><h1>依照妳的節奏。</h1></div>'}${embedded?'':`<section class="commander-settings-link"><div><h2>指揮官成長 · Lv.${commanderProgress(commanderState(save)).level}</h2><p>尚有 ${commanderProgress(commanderState(save)).available} 點，可升級永久共用技能。</p></div><button class="button secondary" data-action="commander">設定共用技能 →</button></section>`}<div class="setting-row"><label for="commander-name">指揮官名稱<small>顯示於頂部 HUD</small></label><input id="commander-name" data-change="commander-name" type="text" maxlength="20" value="${esc(save.preferences.commanderName ?? '指揮官')}" autocomplete="off"></div><div class="setting-row"><label for="music">音樂<small>原創合成配樂</small></label><input id="music" data-change="music" type="range" min="0" max="1" step="0.05" value="${save.preferences.musicVolume}" aria-label="音樂音量"></div><div class="setting-row"><label for="sfx">音效<small>武器、命中與危險提示</small></label><input id="sfx" data-change="sfx" type="range" min="0" max="1" step="0.05" value="${save.preferences.sfxVolume}" aria-label="音效音量"></div><div class="setting-row"><label for="reduced">減少特效<small>降低粒子與動態；不影響戰鬥規則</small></label><input id="reduced" data-change="reduced" type="checkbox" ${save.preferences.reducedEffects ? 'checked' : ''}></div><div class="setting-row"><label for="auto-tactical">自動施放隊長技能<small>場上有敵人且技能就緒時施放</small></label><input id="auto-tactical" data-change="auto-tactical" type="checkbox" ${save.preferences.autoTactical ? 'checked' : ''}></div>${offlineSettings(embedded)}${embedded ? '' : `<div class="save-information"><span class="eyebrow">LOCAL SAVE</span><h2>${esc(status)}</h2><p>進度保存在目前瀏覽器。相同網址可繼續；換裝置或清除網站資料不會同步。</p><button class="button secondary" data-action="save-retry" ${status.startsWith('暫時') ? 'disabled' : ''}>立即儲存</button></div><div class="danger-zone"><span><b>重置本機進度</b><small>刪除關卡紀錄、設定及進行中的行動。</small></span><button class="button danger" data-action="reset-confirm">重置進度</button></div><button class="button secondary" data-action="home">返回作戰中心</button>`}</section>`;
}
