import {readFileSync,writeFileSync,readdirSync,existsSync} from 'node:fs';
import {createHash} from 'node:crypto';
const dir='artifacts/validation/tactical-rework';
const load=(prefix:string,folder='')=>readdirSync(dir+folder).filter(f=>new RegExp(`^${prefix}-\\d+\\.json$`).test(f)).flatMap(f=>JSON.parse(readFileSync(`${dir}${folder}/${f}`,'utf8')) as any[]);
const rows=load('matrix'),probes=load('probes'),rescue=existsSync(`${dir}/rescue`)?load('matrix','/rescue'):[];
const mean=(rs:any[],key:string)=>rs.length?rs.reduce((s,r)=>s+r[key],0)/rs.length:0;
const win=(rs:any[])=>rs.length?rs.filter(r=>r.outcome==='victory').length/rs.length:0;
const pct=(n:number)=>`${(n*100).toFixed(1)}%`;
const group=(rs:any[],key:(r:any)=>string)=>{const g=new Map<string,any[]>();for(const r of rs){const k=key(r);g.set(k,[...(g.get(k)??[]),r]);}return g;};
const cells=['old-old','new-old','old-new','new-new'];
const groups=group(rows,r=>`${r.stage}/${r.mode}`),holdout=rows.filter(r=>r.split==='holdout');
const flags:{type:string;key:string;detail:string}[]=[];
const labels:Record<string,string>={'pressure-not-increased':'壓力未增加','missing-second-solution':'尚未找到兩組通關解','adaptive-not-better':'依敵情策略未占優','paired-win-gap':'配對通關率差距警戒','build-performance-gap':'同用途構築差距警戒','outfit-no-observed-advantage':'換裝尚未觀察到優勢'};
const summaries=[...groups].map(([key,rs])=>{
 const sets=Object.fromEntries(cells.map(cell=>[cell,rs.filter(r=>r.cell===cell&&r.split==='holdout')]));
 const rates=Object.fromEntries(cells.map(cell=>[cell,win(sets[cell])]));
 for(const [oldKey,newKey] of [['old-old','old-new'],['new-old','new-new']])if(sets[oldKey].length&&mean(sets[newKey],'hp')>=mean(sets[oldKey],'hp')&&rates[newKey]>=rates[oldKey]&&!(mean(sets[oldKey],'hp')===0&&mean(sets[newKey],'hp')===0&&mean(sets[newKey],'seconds')<mean(sets[oldKey],'seconds')))flags.push({type:'pressure-not-increased',key,detail:`${oldKey} → ${newKey}: 勝率 ${pct(rates[oldKey])} → ${pct(rates[newKey])}，剩餘防線 ${mean(sets[oldKey],'hp').toFixed(1)} → ${mean(sets[newKey],'hp').toFixed(1)}，結束時間 ${mean(sets[oldKey],'seconds').toFixed(1)} → ${mean(sets[newKey],'seconds').toFixed(1)} 秒`});
 const teams=[0,1].map(team=>{const rs=sets['new-new'].filter(r=>r.team===team);return {team,wins:rs.filter(r=>r.outcome==='victory').length,total:rs.length};});
 const rescueTeams=[0,1].map(team=>{const rs=rescue.filter(r=>`${r.stage}/${r.mode}`===key&&r.team===team&&r.split==='holdout');return {team:team+2,wins:rs.filter(r=>r.outcome==='victory').length,total:rs.length};});
 if([...teams,...rescueTeams].filter(t=>t.wins>0).length<2)flags.push({type:'missing-second-solution',key,detail:[...teams,...rescueTeams].map(t=>`隊伍 ${t.team+1}: ${t.wins}/${t.total}`).join('；')});
 const policy=Object.fromEntries(['concentrated','balanced','adaptive'].map(p=>{const rs=sets['new-new'].filter(r=>r.policy===p);return [p,{win:win(rs),hp:mean(rs,'hp'),seconds:mean(rs,'seconds')}];}));
 if(policy.adaptive.win<=policy.balanced.win&&policy.adaptive.hp<=policy.balanced.hp&&!(policy.adaptive.hp===0&&policy.balanced.hp===0&&policy.adaptive.seconds>policy.balanced.seconds))flags.push({type:'adaptive-not-better',key,detail:`依敵情勝率 ${pct(policy.adaptive.win)}／防線 ${policy.adaptive.hp.toFixed(1)}；平均投資 ${pct(policy.balanced.win)}／${policy.balanced.hp.toFixed(1)}`});
 return {key,rates,teams,rescueTeams,policy,remainingWall:mean(sets['new-new'],'hp'),shield:mean(sets['new-new'],'shield')};
});
for(const [key,rs] of group(holdout,r=>`${r.stage}/${r.mode}/${r.team}/${r.policy}`))for(const [a,b] of [['old-old','new-old'],['old-new','new-new']]){const aa=rs.filter(r=>r.cell===a),bb=rs.filter(r=>r.cell===b);if(Math.abs(win(aa)-win(bb))>.100001)flags.push({type:'paired-win-gap',key,detail:`${a} → ${b}: ${pct(win(aa))} → ${pct(win(bb))}`});}
const purpose=(r:any)=>{const counts:Record<string,number>={};for(const id of r.plan){const branch=id.split('/')[0];counts[branch]=(counts[branch]??0)+1;}return Object.entries(counts).sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0]))[0][0];};
const probeSummary=[...group(probes,r=>`${r.owner}/${r.form}/${r.budget}/${r.scenario}/${purpose(r)}`)].map(([key,rs])=>{
 const active=rs.filter(r=>r.ultimate),passive=rs.filter(r=>!r.ultimate),sorted=[...rs].sort((a,b)=>b.damage-a.damage);
 const best=sorted[0],worst=sorted.at(-1),gap=worst.damage?best.damage/worst.damage-1:0;
 if(gap>.15)flags.push({type:'build-performance-gap',key,detail:`同角色／情境／點數／主要分支，最高與最低有效傷害相差 ${(gap*100).toFixed(1)}%；需連同護盾與控場判讀。`});
 return {key,builds:rs.length,best:best.damage,worst:worst.damage,gap,ultimate:active.length?{damage:mean(active,'damage'),wallLoss:mean(active,'wallLoss'),absorbed:mean(active,'absorbed'),control:mean(active,'control')}:null,passive:passive.length?{damage:mean(passive,'damage'),wallLoss:mean(passive,'wallLoss'),absorbed:mean(passive,'absorbed'),control:mean(passive,'control')}:null};
});
const forms=[...group(probes,r=>`${r.owner}/${r.budget}/${r.scenario}`)].map(([key,rs])=>{const original=rs.filter(r=>r.form.endsWith('original')),summer=rs.filter(r=>r.form.endsWith('summer'));return {key,original:mean(original,'damage'),summer:mean(summer,'damage'),originalShield:mean(original,'absorbed'),summerShield:mean(summer,'absorbed'),originalWallLoss:mean(original,'wallLoss'),summerWallLoss:mean(summer,'wallLoss'),originalControl:mean(original,'control'),summerControl:mean(summer,'control')};});
for(const [owner,rs] of group(forms.filter(r=>r.key.split('/')[1]==='10'),r=>r.key.split('/')[0])){if(!rs.some(r=>r.summer>r.original*1.01||r.summerShield>r.originalShield*1.01||r.summerControl>r.originalControl*1.01||r.summerWallLoss<r.originalWallLoss*.99))flags.push({type:'outfit-no-observed-advantage',key:owner,detail:'10 點七種情境的平均傷害、有效吸收、控場及失血，未觀察到夏日的明顯優勢；需擴充針對性情境或再調整。'});}
const sourceFiles=(path:string):string[]=>readdirSync(path,{withFileTypes:true}).flatMap(e=>e.isDirectory()?sourceFiles(`${path}/${e.name}`):[`${path}/${e.name}`]).sort();
const sourceDigest=createHash('sha256').update(sourceFiles('src').map(f=>f+'\n'+readFileSync(f,'utf8')).join('\n')).digest('hex');
const result={generatedAt:new Date().toISOString(),sourceDigest,complete:rows.length===48240&&probes.length===8848&&rescue.length===4020,expectedMissions:48240,missions:rows.length,rescueMissions:rescue.length,expectedRescueMissions:4020,expectedProbes:8848,probes:probes.length,calibration:rows.filter(r=>r.split==='calibration').length,holdout:holdout.length,timeouts:rows.filter(r=>r.outcome==='timeout').length,restored:rows.filter(r=>r.restored).length,peakEnemies:Math.max(...rows.map(r=>r.peak)),summaries,probeSummary,forms,flags};
writeFileSync(`${dir}/balance-report.json`,JSON.stringify(result,null,2));
let md=`# 戰術技能與全模式平衡驗證\n\n技能版本 0.6.0-dev.1；關卡版本 3。${result.complete?'完整矩陣已完成':'矩陣尚未完成，不能視為驗收通過'}。本地實作，未部署。\n\n## 方法與界線\n\n- 四組配對：舊技能＋舊關卡、 新技能＋舊關卡、舊技能＋新關卡、新技能＋新關卡。舊版為 0.5.0-dev.2／平衡 2。\n- 67 組關卡／模式 × 2 個原裝隊伍 × 3 種配點策略 × 4 組版本 × 30 種子，共 ${rows.length.toLocaleString()}／48,240 場。校準 ${result.calibration.toLocaleString()} 場，獨立驗證 ${holdout.length.toLocaleString()} 場。\n- 校準種子：101 + 106 × i（i=0…19）；獨立驗證：50101 + 106 × i（i=0…9）。前輪 2221…3175 的種子曾用於探索，不作獨立驗證。最終版凍結後才產生此次驗證結果。\n- 隊伍一：凜月、芙蕾、雷娜、希雅、璃音；隊伍二：熾夏、米菈、汐音、希雅、璃音。四人限制各移除璃音。隊長固定首位；配對不更換隊長。\n- 補充 ${rescue.length.toLocaleString()}／4,020 場：隊伍三（米菈、芙蕾、汐音、希雅、熾夏）及隊伍四（米菈、雷娜、汐音、希雅、凜月），米菈隊長、集中投資，所有 67 模式與相同 20＋10 種子。這兩隊由校準種子 S03 探索找到方向，獨立驗證後才計入可行解；不混入四格配對通關率。\n- 集中、平均、依敵情三個確定性策略；依敵情為啟發式，並非已證明的最佳反制。指揮官被動依正常前置關卡進度配置；不是零養成，也不是全滿養成。\n- 技能探針 ${probes.length.toLocaleString()}／8,848 組：八角色、原裝／夏日、4／6／10／14 點、全部可達終點路徑、雙入口與無終極，七種移動敵人情境；敵人有限生命，24 秒增援，終極有首次冷卻，90 秒上限。\n- 探針由同一時刻取得全部測試點數；實際取得時機另由關卡配對呈現。90 秒未結束的探針不是無限控制證據。單角傷害不作跨角色排名；希雅等支援另記錄失血、有效吸收、控場與隊伍配對結果。尚無隔離所有支援收益的因果評估。\n- 壓力比較納入通關率與剩餘防線；若兩組都歸零，另比較存活時間，避免把更早崩潰誤判為壓力相同。\n- 以下「找到解」僅表示至少觀察到一次勝利，不等於穩定通關。15%／10 個百分點是調整警戒，不是玩家通關率目標。\n\n## 結果\n\n平衡驗收仍需調整：${flags.filter(f=>f.type==='missing-second-solution').length} 組關卡／模式尚未觀察到兩組原裝通關解。以下數字描述測試策略，不能等同玩家通關率，也不證明沒有其他可行構築。\n\n${result.timeouts} 場達到清場時間上限；${result.restored} 場曾在配點後還原快照；最高同場敵數 ${result.peakEnemies}。\n\n| 模式 | 舊＋舊 | 新技能＋舊關 | 舊技＋新關 | 新＋新 | 隊伍一勝場 | 隊伍二勝場 | 補充隊伍三／四勝場 | 新版平均有效護盾 |\n|---|---:|---:|---:|---:|---:|---:|---:|---:|\n`;
for(const s of summaries)md+=`| ${s.key} | ${cells.map(c=>pct(s.rates[c])).join(' | ')} | ${s.teams.map(t=>`${t.wins}/${t.total}`).join(' | ')} | ${s.rescueTeams.map(t=>`${t.wins}/${t.total}`).join('；')} | ${s.shield.toFixed(1)} |\n`;
md+='\n上表為獨立驗證集；完整校準結果、每場配點、時間、控場與護盾保留在 matrix-*.json。\n\n## 未達標／需後續調整\n\n';
for(const [kind,rs] of group(flags,r=>r.type))md+=`- ${labels[kind]??kind}：${rs.length} 個警戒項目。\n`;
md+='\n詳細警戒（不刪除失敗樣本）：\n\n';
for(const flag of flags.filter(f=>f.type!=='build-performance-gap'))md+=`- **${labels[flag.type]??flag.type} / ${flag.key}**：${flag.detail}\n`;
md+='\n同情境構築傷害差距警戒及原裝／夏日的情境分布完整列於 balance-report.json；不可把最高傷害當成所有角色的平衡目標。實體手機效能、玩家操作體感、每個關卡兩組穩定解及依敵情策略全面優勢仍需分別判讀，不能以單元測試通過替代。\n\n## 重現\n\n完整重跑使用最新規則，不依賴開發中暫存。此次局部修正的替換範圍與資料摘要保存在 correction-receipt.json：百波跨階段整備，以及使用熾夏新技能的全部樣本；其餘樣本的規則未變。\n\n```sh\nnode --import tsx scripts/document-tactical-rework.ts\n# 一次執行完整矩陣與探針（會重建最終分片）\nnpm run test:tactical -- --workers=8\n# 或個別執行，可用 --shard=0 --shards=8 分成八份（0…7 均需執行）\nnode --import tsx scripts/validate-tactical-balance.ts --shard=0 --shards=8\n# 補充隊伍分成四份（0…3 均需執行）\nnode --import tsx scripts/validate-tactical-balance.ts --rescue --output=artifacts/validation/tactical-rework/rescue --shard=0 --shards=4\n# 探針分成四份（0…3 均需執行）\nnode --import tsx scripts/validate-tactical-probes.ts --shard=0 --shards=4\nnode --import tsx scripts/report-tactical-balance.ts\nnpm run test:rules\nnpm run test:offline:unit\nnode --import tsx scripts/benchmark-simulation.ts\nE2E_PORT=5190 npx playwright test tests/e2e/tactical-rework.spec.ts tests/e2e/skill-network.spec.ts tests/e2e/skill-rework.spec.ts\nnpm run build\n```\n\n舊版資料与快照保留；新開局才採新內容。迭代資料位於 iteration-1／iteration-2，報表只讀取根目錄的最終 matrix／probes。舊技能且關卡未變的樣本可從 iteration-2 快取重用；新技能樣本全部重算。來源摘要：`'+sourceDigest+'`。\n';
const perf='artifacts/validation/0.6.0-dev.1/simulation-pressure.json';if(existsSync(perf)){const p=JSON.parse(readFileSync(perf,'utf8'));md+=`\n效能探針：120 敵人、400 彈體、12 場域，1,800 個核心步進，P95 ${p.p95ProcessingMs.toFixed(2)}ms，33.33ms 預算：${p.passed?'通過':'未通過'}。這是桌面 Node CPU，不能代表實體手機幀率。\n`;}
const mobile=`${dir}/mobile-viewport-performance.json`;if(existsSync(mobile)){const p=JSON.parse(readFileSync(mobile,'utf8'));md+=`\n390px 手機視窗：120 個移動敵人、合法新技能持續運作 15 秒，P95 ${p.p95FrameMs.toFixed(2)}ms，核心前進 ${p.ticks} ticks；錯誤 ${p.errors.length}。${p.passedFrameBudget?'通過':'未通過'} 33.33ms 畫面預算。這是桌面 Chromium，非實體手機；目標回捲與補充防線僅為維持測試密度。\n`;}
const verification=`${dir}/verification.json`;if(existsSync(verification)){const v=JSON.parse(readFileSync(verification,'utf8'));md+=`\n本地檢查：${v.rules.passed} 項規則／存檔測試、${v.offline.passed} 項離線測試、${v.browser.passed} 項瀏覽器測試通過（${v.browser.skipped} 項平台限制略過），打包成功。另保留大量背景模擬同時執行時的效能資料；上述效能數值取背景模擬結束後的複測。\n`;}
writeFileSync('docs/TACTICAL_BALANCE.md',md);console.log(JSON.stringify({complete:result.complete,missions:rows.length,probes:probes.length,flags:flags.length}));
