import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { CHARACTER_TREES, DEEP_NODES } from '../src/data/deep-trees';
import { CHARACTER_MAP } from '../src/data/content';
const dir='artifacts/validation/free-skills';
const balance=JSON.parse(readFileSync(`${dir}/balance.json`,'utf8'));
const matchups=JSON.parse(readFileSync(`${dir}/matchups.json`,'utf8'));
type Row={terminal:string;name:string;budget:number;stageId:string;wallLoss:number;bossSeconds:number;shieldAbsorbed:number;controlSeconds:number;outcome:string;choices:number;subjectNodes:number;restored:boolean;seconds:number};
const rows=balance.rows as Row[];
const mean=(rs:Row[],key:'wallLoss'|'bossSeconds'|'shieldAbsorbed'|'controlSeconds')=>rs.reduce((a,r)=>a+r[key],0)/rs.length;
const lines=[`# 自由技能樹研究與驗證\n\n內容版本 0.3.0-dev.1。這輪保留 14 條樹的不對稱數量，以機制與相同點數預算比較。150 節點與完整前置見 [節點表](FREE_SKILL_NODES.md)。\n\n## 研究方法\n\n正式模擬採 25 個終極 × 主角投入 5／7 點 × 三關 × 十個配對種子，共 1,500 場。種子為 101、211、307、401、503、601、709、809、907、1009；同角色的隊友固定。全隊 24 點、三位核心先交错投資至終極，再配置支援與共用。5 點組完成主角終極，7 點組再投入另一樹兩點，其餘隊伍點數等額減少。\n\n隊長使用正式自動策略，先完成初始冷卻。所有經驗、敵群、傷害、選點均經正常規則；不修改 HP、XP、時間或敵人。每局第 7 點保存／恢復；各終極兩種預算的 S03／101 共 50 份逐命令重播，比較完整狀態摘要。\n\n最低可玩門檻：每個終極至少一種完整構築在一關達 8／10 勝。另比較防線損失、Boss 時間、主角傷害、控場、護盾與修復，避免把輔助角色的低輸出誤判為無用。\n\n固定情境探針使用 5 個合法取得的主角節點，40 秒高生命敵人、不施放隊長技能，與正式通關分開。原五種情境是分散接力、重甲群、縱列、Boss、護盾；針對滿血探針看不到處決與團隊協同的缺口，另加重甲 Boss、20% 殘血、兩位未升級輸出隊友，共 200 個樣本。這些敵群經過人工設定，不是關卡通關證據。\n\n## 正式模擬結果\n\n${rows.filter(r=>r.outcome==='victory').length}／${rows.length} 場通關；所有勝利樣本用完 24 點、主角投入符合 5／7 點，所有保存恢復成功，${balance.replays} 個重播一致。實際戰鬥時間介於 ${Math.min(...rows.map(r=>r.seconds)).toFixed(1)}–${Math.max(...rows.map(r=>r.seconds)).toFixed(1)} 秒。\n\n下表固定 S03、主角 5 點、十個種子平均；不同角色隊伍不完全相同，跨角色數值不能直接作為角色排名。防線損失是累計 HP 傷害，不扣回後續修復，護盾吸收則獨立記錄。\n\n| 角色／終極 | 樹節點數 | 防線損失 | Boss 擊殺秒數 | 護盾吸收 | 控場秒數 |\n| --- | ---: | ---: | ---: | ---: | ---: |`];
for(const t of DEEP_NODES.filter(n=>n.kind==='ultimate')){
  const rs=rows.filter(r=>r.terminal===t.id&&r.budget===5&&r.stageId==='S03');
  lines.push(`| ${t.ownerId==='common'?'共用':CHARACTER_MAP[t.ownerId].name}／${t.name} | ${CHARACTER_TREES.find(x=>x.id===t.treeId)!.nodes.length} | ${mean(rs,'wallLoss').toFixed(1)} | ${mean(rs,'bossSeconds').toFixed(1)} | ${mean(rs,'shieldAbsorbed').toFixed(1)} | ${mean(rs,'controlSeconds').toFixed(1)} |`);
}
lines.push(`\n## 目前判讀\n\n- 通關率已達飽和：這批策略不能證明哪棵樹最強，亦不足以宣稱難度或所有自由搭配都平衡。完整戰局中混入強力隊友，也可能掩蓋主角較弱的路徑。\n- 不對稱數量暫保留。兩樹角色與三樹角色都有可用構築；樹多提供更多選擇，但同局仍共享 24 點，沒有證據支持為了總數相同而增減節點。這不是證明節點數絕對沒有優勢，仍需真人選點率與更多隊伍檢查。\n- 重甲 Boss 探針中，凜月「絕對零距」約 4,395 傷害，長線「天際線斷擊」約 4,065；普通單體滿血探針的順序相反。長線群傷與核心破甲確有不同適用場景。\n- 「因果狙擊」在殘血群探針約 9,904 傷害，滿血密集群約 4,214。該提升證實處決條件生效，但不代表它在所有場合優於長線。璃音「終焉追獵」同樣在殘血探針提升，死亡轉移則由規則測試驗證。\n- S03 的米菈「星環反衝」代表構築平均防線損失約 34，Boss 約 43.5 秒；希雅「六角天幕」約 30 損失、343 護盾吸收，Boss 約 46.9 秒。防守價值不能只看傷害。\n- 仍需關注：燃燒／爆破的長期性價比、同樹雙終極的選擇率、因果狙擊及弱點轉移在真人局的利用程度。200 個探針提供診斷，不以它們取代可玩性與真人趣味性驗收。\n\n原始資料：\n\n- [1,500 場資料與分組](../artifacts/validation/free-skills/balance.json)\n- [200 個情境探針](../artifacts/validation/free-skills/matchups.json)\n- [交付驗證索引](../artifacts/validation/free-skills/release-summary.json)\n\n## 工程驗證\n\n驗證結果在交付時寫入 release-summary.json。包括規則與本地存檔、兩個瀏覽器手機操作、三關完整新版本重播、六位隊長首次冷卻與 1×／3× 動畫、0.2 三選一與 0.1 A/B 舊局回歸、正式 build 無開發入口與實際時間升級／恢復。\n\n60 秒即時 3× 壓測使用 120 名不死敵人、400 顆持續敵彈與至少 12 場域，保持真實移動、攻擊、自動技能、渲染和存檔。該測試是人工壓力場景，效能結果不算正常戰局勝率，也不是實體手機量測。\n\n目前仍缺真實手機硬體與真人趣味性測試；沒有把桌面 Chromium／WebKit 的手機視窗模擬宣稱為真機驗收。`);
if(existsSync(`${dir}/release-summary.json`)){
  const r=JSON.parse(readFileSync(`${dir}/release-summary.json`,'utf8'));
  lines.push(`\n## 最終交付結果\n\n- ${r.rules.passed} 項規則／存檔測試通過，包含四個內容版本與全部終極前置。\n- 最新回歸結果合併為 ${r.browser.passed} 項通過、${r.browser.skipped} 項略過；略過為 WebKit 的 Chromium 專用效能情境。舊版本測試明確指定舊內容，新版另驗證自由選點、三關重播、六人首次冷卻及技能演出。\n- 60 秒 3× 即時壓測 p95 ${r.live3x.p95FrameTimeMs.toFixed(1)} ms，${r.live3x.ticksPerSecond.toFixed(2)} tick／秒，預警遺失 ${r.live3x.warningMissingFrames} 幀；最少 ${r.live3x.minEnemies} 敵人、${r.live3x.minProjectiles} 敵彈與 ${r.live3x.minFields} 場域。\n- 正式版無開發 API；10 Mbps／100 ms RTT 下首頁約 ${(r.production.homeInteractiveMs/1000).toFixed(2)} 秒可操作、戰場約 ${(r.production.battleReadyMs/1000).toFixed(2)} 秒載入。實際時間取得升級，花 1 點後重整成功，首次自動技能在第 ${r.production.firstCastTick/30} 秒施放，無頁面錯誤或失敗請求。\n- 素材清單與正式 build 通過。早期失敗測試及修正紀錄保留於 regression／fixes，最終隊長與壓測紀錄在 captain-final／pressure-final。\n\n[手機技能樹](../artifacts/validation/free-skills/fixes/screenshots/chromium-tree-320.png) · [樹狀連線](../artifacts/validation/free-skills/fixes/screenshots/chromium-tree-768.png) · [隊長技能 3×](../artifacts/validation/free-skills/captain-final/screenshots/chromium-C05-cold-skill-3x.png)`);
}
writeFileSync('docs/FREE_SKILL_VALIDATION.md',lines.join('\n').replace('交错','交錯')+'\n');
console.log(`Reported ${rows.length} legal runs and ${matchups.rows.length} probes`);
