import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { resolve } from 'node:path';
import assert from 'node:assert/strict';
const dir='artifacts/validation/free-skills';
const read=(p:string)=>JSON.parse(readFileSync(`${dir}/${p}`,'utf8'));
interface Suite{file?:string;specs?:{title:string;file:string;tests:{projectName:string;results:{status:string}[]}[]}[];suites?:Suite[]}
const merged=new Map<string,{file:string;title:string;browser:string;status:string;evidence:string}>();
const regressions=['regression','fixes','captain-final','pressure-final'];
for(const group of regressions){const report=read(`${group}/browser-results/results.json`);const visit=(suite:Suite)=>{for(const spec of suite.specs??[])for(const t of spec.tests){const key=`${spec.file}:${spec.title}:${t.projectName}`;merged.set(key,{file:spec.file,title:spec.title,browser:t.projectName,status:t.results.at(-1)?.status??'missing',evidence:`${group}/browser-results/results.json`});}suite.suites?.forEach(visit);};report.suites.forEach(visit);}
const browserCases=[...merged.values()],failed=browserCases.filter(t=>!['passed','skipped'].includes(t.status));assert.deepEqual(failed,[]);
assert.equal(browserCases.length,150);assert.equal(browserCases.filter(t=>t.status==='skipped').length,3);
const balance=read('balance.json'),probes=read('matchups.json'),production=read('production/smoke.json'),assets=read('final-assets/asset-budget.json'),pressure=read('pressure-final/live-3x-performance.json');
assert.equal(balance.rows.length,1500);assert.ok(balance.playable);assert.equal(balance.replays,50);assert.ok(balance.rows.every((r:{restored:boolean;choices:number;subjectNodes:number;budget:number})=>r.restored&&r.choices===24&&r.subjectNodes===r.budget));assert.equal(probes.rows.length,200);
assert.ok(production.passed&&assets.passed&&pressure.passed);assert.ok(production.partialPointRecovery&&production.firstCastTick>=production.initialCooldownTicks);
const allFiles=(p:string):string[]=>readdirSync(p,{withFileTypes:true}).flatMap(e=>e.isDirectory()?allFiles(resolve(p,e.name)):[resolve(p,e.name)]).sort();
const sourceDigest=createHash('sha256').update(JSON.stringify(allFiles(resolve('src')).map(p=>[p.replace(`${process.cwd()}/`,''),readFileSync(p,'utf8')]))).digest('hex');assert.equal(pressure.sourceDigest,sourceDigest);
for(const file of ['desktop-render-performance.json','desktop-render-performance-dynamic.json']){const render=read(`pressure-final/browser-results/${file}`);assert.ok(render.desktopRenderPassed);assert.equal(render.sourceDigest,sourceDigest);}
const rulesLog=readFileSync(`${dir}/rules-final.log`,'utf8');assert.match(rulesLog,/254 passed \(254\)/);
const result={contentVersion:'0.3.0-dev.1',measuredAt:new Date().toISOString(),sourceDigest,passed:true,rules:{passed:254,evidence:'rules-final.log'},browser:{total:browserCases.length,passed:browserCases.filter(t=>t.status==='passed').length,skipped:3,skipReason:'Chromium-only desktop performance scenarios are skipped on WebKit.',cases:browserCases},balance:{runs:1500,wins:balance.rows.filter((r:{outcome:string})=>r.outcome==='victory').length,fullReplays:50,saveRecoveries:1500,allBudgetsValid:true,evidence:'balance.json'},matchups:{runs:200,evidence:'matchups.json',limitation:probes.limitation},production,assets,live3x:{p95FrameTimeMs:pressure.p95FrameTimeMs,ticksPerSecond:pressure.ticksPerSecond,warningMissingFrames:pressure.warningMissingFrames,minEnemies:pressure.minEnemies,minProjectiles:pressure.minProjectiles,minFields:pressure.minFields,evidence:'pressure-final/live-3x-performance.json'},performanceSourceNote:'Live 3x began before a HUD event text color change from #435e61 to #c1e7df. Simulation and geometry were unchanged; subsequent paused and dynamic render checks use the final CSS. Source digests identify the final source snapshot.',priorAttempts:{retained:true,notes:'Initial regression exposed outdated immediate-cast and 18-point fixture assumptions. The animation wait also needed to finish legitimate XP allocations and await its asynchronous predicate. Fixture fixes and final reruns are preserved; no failing result was overwritten. Gameplay emergency-repair counter was fixed to begin at purchase and covered by a regression test.'},limitations:['Desktop Chromium and WebKit with mobile viewports are not physical-device measurements.','All representative builds winning does not prove every squad or branch combination is balanced. Human playtesting remains.','Equipment drops remain deferred; no permanent stat progression was added.']};
writeFileSync(`${dir}/release-summary.json`,JSON.stringify(result,null,2));console.log(JSON.stringify({passed:result.passed,rules:254,browserPassed:result.browser.passed,browserSkipped:3,simulations:1500,replays:50,probes:200,productionPassed:true,p95:pressure.p95FrameTimeMs}));
