import {describe,it,expect} from 'vitest';
import {createRun,stepRun} from '../../src/sim/engine';
import {createEnemy,emit} from '../../src/sim/combat';
import {AreaCueStore,isAreaEvent} from '../../src/game/area-cues';
import {stepUltimates,ultimateNodeId} from '../../src/sim/ultimates';
import {deepTreesFor} from '../../src/data/deep-trees';
import {ultimateForForm} from '../../src/data/reworked-skills';
import {deployMine,detonateMines} from '../../src/sim/special-weapons';
import {stepWeapons} from '../../src/sim/weapons';
import type {CharacterId,DamagePacket} from '../../src/sim/types';
const packet=(id:CharacterId='C05'):DamagePacket=>({source:id,skill:'micro-missile',raw:100,damageType:'thermal',armorIgnore:0,shieldMultiplier:1});
function scene(id:CharacterId='C05',version?:string){const s=createRun({stageId:'S01',squadIds:[id],captainId:id,seed:5},version);s.spawnCursor=s.spawnPlan.length;s.bossSpawned=true;s.pauseReasons=[];s.phase='running';s.weapons.forEach(w=>w.nextAttack=1e9);s.enemies=[];for(const x of [100,143,240]){const e=createEnemy(s,'E03',x,300,0);e.hp=e.maxHp=100000;e.shield=e.armor=e.speed=0;}s.events=[];return s;}
describe('actual attack footprints',()=>{
 it('mine detonation footprint matches real deployed mine and affected enemies',()=>{const s=scene('C07');const target=s.enemies[0];expect(deployMine(s,s.weapons[0],target,packet('C07'),58)).toBe(true);const mine={...s.mines![0]};expect(s.events.some(isAreaEvent)).toBe(false);expect(detonateMines(s,1)).toBe(true);const event=s.events.find(e=>e.skill==='mine'&&e.kind==='explosion')!;expect(event).toMatchObject({x:mine.x,y:mine.y,radius:mine.radius,source:'C07'});expect(event.affectedIds).toEqual(s.enemies.slice(0,2).map(e=>e.id));expect(s.mines).toHaveLength(0);});
 it('magnetic burst footprint comes from the same real target snapshot as damage',()=>{const s=scene('C02');s.treeNodes=['C02-B4/0'];s.enemies[0].arcCharges=2;s.weapons[0].nextAttack=0;stepWeapons(s);const burst=s.events.find(e=>e.kind==='explosion'&&e.skill==='magnetic-burst')!;expect(burst).toMatchObject({x:100,y:300,radius:60,source:'C02'});expect(burst.affectedIds).toEqual(s.enemies.slice(0,2).map(e=>e.id));});

 it('repulse depicts the actual wall band, not a fictional circle',()=>{const q=new AreaCueStore();q.update([{seq:1,tick:1,kind:'explosion',skill:'repulse',x:195,y:440,radius:90}],0);expect(q.cues[0].event).toMatchObject({areaShape:'wall-band',y:365});});
 it('impact emits exact radius, position and damaged IDs only at impact',()=>{const s=scene();s.projectiles.push({id:s.nextEntityId++,x:195,y:490,tx:100,ty:300,vx:0,vy:0,expires:100,hitIds:[],remaining:1,falloff:[1],radius:4,blastRadius:40,packet:packet(),enemyDamage:0,enemySource:null,impactAt:2});stepRun(s);expect(s.events.some(isAreaEvent)).toBe(false);stepRun(s);const e=s.events.find(e=>e.kind==='explosion')!;expect(e).toMatchObject({x:100,y:300,radius:40,skill:'micro-missile',tick:2});expect(e.affectedIds).toEqual(s.enemies.slice(0,2).map(e=>e.id));expect(s.enemies[0].hp).toBeLessThan(100000);expect(s.enemies[1].hp).toBeLessThan(100000);expect(s.enemies[2].hp).toBe(100000);});
 it.each([undefined])('every delayed pulse emits impact in %s',version=>{const s=scene('C05',version);for(let at=1;at<=3;at++)s.scheduled.push({at,x:100+at,y:300,radius:60,packet:{...packet(),skill:'tactical'},enemyDamage:0,enemySource:null});for(let i=0;i<3;i++)stepRun(s);expect(s.events.filter(e=>e.kind==='explosion').map(e=>[e.tick,e.x,e.radius])).toEqual([[1,101,60],[2,102,60],[3,103,60]]);});
 for(const id of ['C01','C02','C05'] as const)for(const theme of ['original','summer'] as const)it(`${id}-${theme} ultimate geometry`,()=>{const s=scene(id);s.config.forms={[id]:`${id}-${theme}`};const tree=deepTreesFor(id,s).find(t=>t.nodes.some(n=>n.id===ultimateNodeId(id,s)))!;s.treeNodes=tree.nodes.slice(0,5).map(n=>n.id);s.weapons[0].ultimateReadyAt=0;stepUltimates(s);const u=ultimateForForm(id,`${id}-${theme}`),impact=s.events.find(e=>e.kind==='explosion'&&e.skill==='ultimate')!;expect(impact.radius).toBe(u.radius);expect(impact.affectedIds!.length).toBeGreaterThan(0);expect(s.scheduled.length).toBe(u.pulses-1);});
 it('penetration width is real; single-target ultimate has no circle',()=>{const s=scene('C03');s.weapons[0].nextAttack=0;stepWeapons(s);expect(s.events.find(e=>e.areaShape==='line')).toMatchObject({x:195,y:490,radius:7});expect(isAreaEvent({seq:1,tick:1,kind:'tactical',source:'C03',x:100,y:300,radius:70})).toBe(false);});
 it('retains 40 real blasts under hit pressure; deduplicates and expires',()=>{const s=scene();for(let i=0;i<40;i++)emit(s,{kind:'explosion',x:i*5,y:250,radius:30,source:'C05'});for(let i=0;i<200;i++)emit(s,{kind:'hit',x:0,y:0});const q=new AreaCueStore();q.update(s.events,100);expect(q.cues).toHaveLength(40);q.update(s.events,200);expect(q.cues).toHaveLength(40);q.update([],540);expect(q.cues).toHaveLength(0);});
});
