import './ui/commander.css';
import './ui/styles.css';
import './ui/collection.css';
import './ui/mobile.css';
import './ui/mobile-secondary.css';
import './ui/mobile-combat.css';
import './ui/mobile-game.css';
import './ui/mobile-notice.css';
import './ui/roster.css';
import './ui/tactical-tree.css';
import './ui/battle-focus.css';
import './ui/portrait.css';
import './ui/squad-lobby.css';
import './ui/game-shell.css';
import './ui/operation-home.css';
import './ui/recruitment-v2.css';
import './ui/tactical-command.css';
import './ui/readability.css';
import './ui/personnel-skills.css';
import './ui/offline.css';
import { offlineGame } from './offline';
import { GameApp } from './ui/app';

const root = document.getElementById('app');
if (!root) throw new Error('找不到遊戲掛載點');
void offlineGame.start();
void new GameApp(root).init();
